// <auto-generated />
using System;
using AnimalShelter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterDbContext))]
    [Migration("20250515164233_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.AnimalBreed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalViewId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalViewId");

                    b.ToTable("AnimalBreeds");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.AnimalStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnimalStatuses");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.AnimalView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AnimalViews");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.AppStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppStatuses");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.EmployeePost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmployeePosts");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.RoleUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoleUsers");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Adoption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdoptionApplicationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AdoptionDate")
                        .HasColumnType("date");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdoption")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AdoptionApplicationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Adoptions");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.AdoptionApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppStatusId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<string>("LivingConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("AppStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("AdoptionalApplications");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("AnimalBreedId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalStatusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalViewId")
                        .HasColumnType("uuid");

                    b.Property<string>("DistinctiveFeatures")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("Photos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AnimalBreedId");

                    b.HasIndex("AnimalStatusId");

                    b.HasIndex("AnimalViewId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeePostId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeePostId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.TemporaryPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateAnimalReturn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateAnimalTake")
                        .HasColumnType("date");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("TemporaryPlacement");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleUserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MoreInformation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Dictionary.AnimalBreed", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.AnimalView", "AnimalView")
                        .WithMany()
                        .HasForeignKey("AnimalViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalView");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Adoption", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Main.AdoptionApplication", "AdoptionApplication")
                        .WithMany()
                        .HasForeignKey("AdoptionApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Main.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdoptionApplication");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.AdoptionApplication", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Main.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.AppStatus", "AppStatus")
                        .WithMany()
                        .HasForeignKey("AppStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Main.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("AppStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Animal", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.AnimalBreed", "AnimalBreed")
                        .WithMany()
                        .HasForeignKey("AnimalBreedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.AnimalStatus", "AnimalStatus")
                        .WithMany()
                        .HasForeignKey("AnimalStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.AnimalView", "AnimalView")
                        .WithMany()
                        .HasForeignKey("AnimalViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalBreed");

                    b.Navigation("AnimalStatus");

                    b.Navigation("AnimalView");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Employee", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.EmployeePost", "EmployeePost")
                        .WithMany()
                        .HasForeignKey("EmployeePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Main.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeePost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.TemporaryPlacement", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Main.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimalShelter.Models.Domain.Main.Volunteer", "Volunteer")
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.User", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Dictionary.RoleUser", "RoleUser")
                        .WithMany()
                        .HasForeignKey("RoleUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleUser");
                });

            modelBuilder.Entity("AnimalShelter.Models.Domain.Main.Volunteer", b =>
                {
                    b.HasOne("AnimalShelter.Models.Domain.Main.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
